# .github/workflows/ci-cd-template.yml

name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  # Define global environment variables here
  NODE_ENV: production

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add build steps (example: npm install, build)
      # - name: Install dependencies
      #   run: npm ci

      # - name: Build project
      #   run: npm run build

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add test steps
      # - name: Run tests
      #   run: npm test

  notify:
    name: Discord Notification
    needs: [build, test]
    runs-on: ubuntu-latest
    if: always() # Change to 'failure()' for failures only
    steps:
      - name: Notify Discord
        uses: Ilshidur/action-discord@0.4.0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: 'CI/CD Pipeline completed. Status: ${{ job.status }}'
